import {
  MessageSquare,
  FileText,
  Theater,
  PenTool,
  Mic,
  Image,
  Route,
  Brackets,
  Search,
  Zap,
  Waves,
  Wand2,
  BookOpen,
  Headphones,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export interface PracticeMode {
  id: string;
  label: string;
  description: string;
  example: string;
  colorVar: string;
  icon: LucideIcon;
  to: string;
  image?: string;
  highlighted?: boolean;
}

export const exerciseModes: readonly PracticeMode[] = [
  {
    id: 'phrases',
    label: 'Frases',
    description: 'Receba uma situação e fale a frase em inglês',
    example: 'Você quer pedir um café. Como você diria isso?',
    colorVar: 'phrases',
    icon: MessageSquare,
    to: '/exercises?mode=phrases',
    image: '/images/modes/phrases.png',
  },
  {
    id: 'texts',
    label: 'Textos',
    description: 'Receba um texto em português e fale em inglês com naturalidade',
    example: 'Leia um parágrafo sobre viagens e fale em inglês',
    colorVar: 'texts',
    icon: FileText,
    to: '/exercises?mode=texts',
    image: '/images/modes/texts.png',
  },
  {
    id: 'situations',
    label: 'Situações',
    description: 'Responda a um cenário real em inglês',
    example: 'Você está num restaurante. Como pede a conta?',
    colorVar: 'situations',
    icon: Theater,
    to: '/exercises?mode=situations',
    image: '/images/modes/situations.png',
  },
  {
    id: 'scripts',
    label: 'Scripts',
    description: 'Gere diálogos para praticar como um ator, lendo e atuando as falas',
    example: 'Atue uma entrevista técnica com um recrutador do Google',
    colorVar: 'scripts',
    icon: PenTool,
    to: '/scripts',
    image: '/images/modes/scripts.png',
  },
] as const;

export const conversationModes: readonly PracticeMode[] = [
  {
    id: 'simulation',
    label: 'Simulação ao Vivo',
    description: 'Converse em tempo real com a IA por voz ou pratique entrevistas',
    example: 'Simule uma conversa num café em Londres',
    colorVar: 'simulation',
    icon: Mic,
    to: '/live',
    image: '/images/modes/simulation.png',
  },
  {
    id: 'visual',
    label: 'Desafio Visual',
    description: 'Veja uma imagem e descreva o que acontece',
    example: 'Descreva a cena de uma foto de mercado',
    colorVar: 'visual',
    icon: Image,
    to: '/exercises?mode=visual',
    image: '/images/modes/visual.png',
  },
] as const;

export const trailsMode: PracticeMode = {
  id: 'trails',
  label: 'Trilhas',
  description: 'Siga trilhas guiadas por situações da vida real',
  example: 'Complete uma trilha de viagem: aeroporto, hotel, restaurante',
  colorVar: 'trails',
  icon: Route,
  to: '/paths',
  image: '/images/modes/trails.png',
};

/**
 * Wave 4 — focused drills generated by the Master (or random fallback).
 * These are short, signal-dense exercises that target specific skills.
 * They live under "Treinos Dirigidos" in the Practice Hub.
 */
export const focusedDrillModes: readonly PracticeMode[] = [
  {
    id: 'cloze',
    label: 'Complete a Frase',
    description: 'Ouça uma frase com uma palavra faltando e fale a palavra em voz alta',
    example: '"I was *BEEP* when my phone rang." → diga "reading"',
    colorVar: 'cloze',
    icon: Brackets,
    to: '/exercises?mode=cloze',
  },
  {
    id: 'spotting',
    label: 'Acho do Erro',
    description: 'Ouça uma frase com um erro plantado e diga a versão correta',
    example: '"She go to work every day" → "She goes to work every day"',
    colorVar: 'spotting',
    icon: Search,
    to: '/exercises?mode=spotting',
  },
  {
    id: 'reaction',
    label: 'Reação Rápida',
    description: 'Responda a provocações curtas em inglês com velocidade — drill de automatismo',
    example: '"Your friend lost their keys" → "Oh no, did you check your car?"',
    colorVar: 'reaction',
    icon: Zap,
    to: '/exercises?mode=reaction',
  },
  {
    id: 'shadowing',
    label: 'Sombra Ativa',
    description: 'Ouça uma frase e repita imitando ritmo, pausas e contrações',
    example: '"Honestly, I kinda think we should just go." → repita igual',
    colorVar: 'shadowing',
    icon: Waves,
    to: '/exercises?mode=shadowing',
  },
  {
    id: 'reformulation',
    label: 'Reformulação',
    description: 'Reformule uma frase rígida em inglês mais casual, curto ou natural',
    example: '"I would like to request more time" → "Any way I could get more time?"',
    colorVar: 'reformulation',
    icon: Wand2,
    to: '/exercises?mode=reformulation',
  },
  {
    id: 'narrative',
    label: 'Continue a História',
    description: 'Ouça um começo de história e continue em inglês por até 60 segundos',
    example: '"It was just before sunrise when..." → continue livremente',
    colorVar: 'narrative',
    icon: BookOpen,
    to: '/exercises?mode=narrative',
  },
  {
    id: 'listening',
    label: 'Escuta Direcionada',
    description: 'Ouça um trecho falado e responda perguntas sobre o que entendeu',
    example: 'Passagem de 90 segundos + 2-3 perguntas de compreensão',
    colorVar: 'listening',
    icon: Headphones,
    to: '/exercises?mode=listening',
  },
] as const;

export const allModes: readonly PracticeMode[] = [
  ...exerciseModes,
  ...conversationModes,
  ...focusedDrillModes,
  trailsMode,
];
